// product-data.js
// VYBECO x LG SUBSCRIBE — DATA PRODUK

const CATEGORY_ORDER = [
  ['refrigerator', 'Refrigerator'],
  ['water-purifier', 'Water Purifier'],
  ['air-purifier', 'Air Purifier'],
  ['washer', 'Washer'],
  ['dryer', 'Dryer'],
  ['washtower', 'WashTower'],
  ['aircond', 'Air Conditioner'],
  ['tv', 'TV'],
  ['soundbar', 'Soundbar'],
  ['styler', 'Styler'],
  ['dishwasher', 'Dishwasher'],
  ['vacuum', 'Vacuum'],
  ['dehumidifier', 'Dehumidifier'],
];

const ICONS = {
  'refrigerator': '🧊',
  'water-purifier': '💧',
  'air-purifier': '🌬️',
  'washer': '🧺',
  'dryer': '🌤️',
  'washtower': '🧺',
  'aircond': '❄️',
  'tv': '📺',
  'soundbar': '🔊',
  'styler': '👔',
  'dishwasher': '🍽️',
  'vacuum': '🧹',
  'dehumidifier': '💨',
};

const PRODUCTS = [
  // === REFRIGERATOR ===
  {
    cat: 'refrigerator',
    model: 'GC-L257KQKR',
    name: '641L Side-by-Side',
    poster: 'assets/img/refrigerator/GC-L257KQKR.jpg',
    price: 'RM220 / bulan',
    desc: 'Peti sejuk side-by-side besar dengan dispenser ais & air – sesuai keluarga besar.',
    specs: [
      'Smart Inverter Compressor – jimat tenaga & senyap.',
      'LinearCooling+ – suhu sekata, makanan tahan lama.',
      'UVnano Dispenser – air bersih.',
    ],
    benefits: [
      'Penjimatan bil elektrik sehingga 32%.',
      'Hygiene tinggi, kurang bau.',
    ],
  },
  {
    cat: 'refrigerator',
    model: 'GC-J257SQNW',
    name: '635L Side-by-Side UVnano',
    poster: 'assets/img/refrigerator/GC-J257SQNW.jpg',
    price: 'RM260 / bulan',
    desc: 'Side-by-side dengan fokus kebersihan UVnano & Hygiene Fresh+.',
    specs: [
      'UVnano pada nozzle – kurang bakteria.',
      'Door-in-Door – akses pantas tanpa bocor sejuk.',
    ],
    benefits: ['Bau segar, sesuai keluarga alergi.'],
  },
  {
    cat: 'refrigerator',
    model: 'GN-F452PQAK',
    name: '491L Top Freezer',
    poster: 'assets/img/refrigerator/GN-F452PQAK.jpg',
    price: 'RM160 / bulan',
    desc: 'Top-freezer kompak dengan dispenser air terbina.',
    specs: ['DoorCooling+ – sejuk sekata.', 'Kapasiti 491L.'],
    benefits: ['Jimat ruang untuk apartment / condo.'],
  },
  {
    cat: 'refrigerator',
    model: 'GC-B24FFCPB',
    name: '665L Multi-Door',
    poster: 'assets/img/refrigerator/GC-B24FFCPB.jpg',
    price: 'RM130 / bulan',
    desc: 'Multi-door besar untuk organisasi makanan.',
    specs: ['InstaView Door-in-Door.', 'Express Freeze.'],
    benefits: ['Lihat stok tanpa buka pintu penuh.'],
  },
  {
    cat: 'refrigerator',
    model: 'GV-K25FFGER',
    name: '612L White Glass',
    poster: 'assets/img/refrigerator/GV-K25FFGER.jpg',
    price: 'RM180 / bulan',
    desc: 'Reka bentuk kaca putih moden dengan kapasiti besar.',
    specs: ['Glass finish premium.', 'Smart Diagnosis.'],
    benefits: ['Estetik dapur premium, mudah dibersihkan.'],
  },
  {
    cat: 'refrigerator',
    model: 'GC-G22FFQAB',
    name: '508L Multi-Door',
    poster: 'assets/img/refrigerator/GC-G22FFQAB.jpg',
    price: 'RM160 / bulan',
    desc: 'Multi-door dengan dispenser air & ais.',
    specs: ['ThinQ AI – kawal dari app.', 'Multi Air Flow.'],
    benefits: ['Mudah kawal suhu dari telefon.'],
  },
  {
    cat: 'refrigerator',
    model: 'GR-L257KQKR',
    name: '657L InstaView',
    poster: 'assets/img/refrigerator/GR-L257KQKR.jpg',
    price: 'RM240 / bulan',
    desc: 'Peti sejuk InstaView — ketuk 2x untuk lihat dalam tanpa buka pintu.',
    specs: ['InstaView Door-in-Door.', 'Hygiene Fresh+.'],
    benefits: ['Kurang pembaziran sejuk, lebih jimat tenaga.'],
  },
  {
    cat: 'refrigerator',
    model: 'PTOX24FFC7R',
    name: 'Premiere Glass Series',
    poster: 'assets/img/refrigerator/PTOX24FFC7R.jpg',
    price: 'RM260 / bulan',
    desc: 'Refrigerator kaca premium untuk dapur moden.',
    specs: ['Premium glass door.', 'Smart inverter.'],
    benefits: ['Matching dengan konsep dapur moden / minimal.'],
  },

  // === WATER PURIFIER ===
  {
    cat: 'water-purifier',
    model: 'WU525BS',
    name: 'Atom-U Hot/Cold',
    poster: 'assets/img/water-purifier/WU525BS.jpg',
    price: 'RM110 / bulan',
    desc: 'Penapis tanpa tangki dengan suhu on-demand.',
    specs: ['4-lapis penapisan RO.', 'ThinQ app control.'],
    benefits: ['Air bersih 99.99%, jimat beli air botol.'],
  },
  {
    cat: 'water-purifier',
    model: 'WD518AN',
    name: 'Atom-V Compact',
    poster: 'assets/img/water-purifier/WD518AN.jpg',
    price: 'RM70 / bulan',
    desc: 'Kompak untuk dapur kecil / apartment.',
    specs: ['4 warna pilihan.', 'Auto steril dalaman.'],
    benefits: ['Tak makan ruang, sesuai countertop kecil.'],
  },
  {
    cat: 'water-purifier',
    model: 'WS410GN',
    name: 'S2 Slim Stand Hot/Cold',
    poster: 'assets/img/water-purifier/WS410GN.jpg',
    price: 'RM110 / bulan',
    desc: 'Slim stand dengan hot/cold untuk ruang tamu / dapur.',
    specs: ['Mineral boost.', 'UV steril di nozzle.'],
    benefits: ['Rasa air lebih natural & bersih.'],
  },
  {
    cat: 'water-purifier',
    model: 'WS510SN',
    name: 'S1 Slim Hot/Ambient/Cold',
    poster: 'assets/img/water-purifier/WS510SN.jpg',
    price: 'RM130 / bulan',
    desc: '3 suhu (hot/room/cold) dalam 1 unit slim.',
    specs: ['RO + UV.', 'Smart display suhu & status.'],
    benefits: ['Sesuai keluarga sibuk – buat susu, minum panas & sejuk.'],
  },
  {
    cat: 'water-purifier',
    model: 'WD210MN',
    name: 'MX Hot/Ambient',
    poster: 'assets/img/water-purifier/WD210MN.jpg',
    price: 'RM60 / bulan',
    desc: 'MX series untuk fokus kebersihan air.',
    specs: ['Multi-stage filter.', 'Auto clean dalaman.'],
    benefits: ['Kurang maintenance, air konsisten bersih.'],
  },
  {
    cat: 'water-purifier',
    model: 'WD516AN',
    name: 'MX Slim Compact',
    poster: 'assets/img/water-purifier/WD516AN.jpg',
    price: 'RM80 / bulan',
    desc: 'Model tambahan MX slim untuk ruang kecil.',
    specs: ['Tankless design.', 'Filter mudah tukar.'],
    benefits: ['Nampak kemas, sesuai dapur minimal.'],
  },

  // === AIR PURIFIER ===
  {
    cat: 'air-purifier',
    model: 'AS10GDBYO',
    name: 'Alpha Pet Dual Booster',
    poster: 'assets/img/air-purifier/AS10GDBYO.jpg',
    price: 'RM105 / bulan',
    desc: '360° purifier untuk ruang besar dengan pet filter.',
    specs: ['HEPA H13 + deodorizing filter.', 'PM1.0 sensor.'],
    benefits: ['Kurang alergi & bau haiwan peliharaan.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS60GHWGO',
    name: '360° Standard',
    poster: 'assets/img/air-purifier/AS60GHWGO.jpg',
    price: 'RM140 / bulan',
    desc: 'Model pertengahan untuk bilik / ruang tamu.',
    specs: ['True HEPA.', 'Sleep mode senyap.'],
    benefits: ['Udara bersih 99.97% dari habuk halus.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS20GPBK0',
    name: 'AeroFurniture',
    poster: 'assets/img/air-purifier/AS20GPBK0.jpg',
    price: 'RM160 / bulan',
    desc: 'Meja + purifier hybrid untuk ruang moden.',
    specs: ['HEPA + pre-filter.', 'Compact design.'],
    benefits: ['Jimat ruang & nampak estetik.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS65GDBYO',
    name: 'Alpha Pet Single Booster',
    poster: 'assets/img/air-purifier/AS65GDBYO.jpg',
    price: 'RM75 / bulan',
    desc: 'Single booster untuk owner haiwan peliharaan.',
    specs: ['Pet mode khas.', 'Auto clean filter.'],
    benefits: ['Kurang bulu & bau haiwan.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS10GDWBO',
    name: '360° Dual Booster',
    poster: 'assets/img/air-purifier/AS10GDWBO.jpg',
    price: 'RM100 / bulan',
    desc: 'Dual booster untuk edaran udara cepat.',
    specs: ['360° air intake.', 'Plasmaster Ionizer.'],
    benefits: ['Udara bersih lebih cepat untuk ruang besar.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS55GG',
    name: 'Aero Booster',
    poster: 'assets/img/air-purifier/AS55GG.jpg',
    price: 'RM65 / bulan',
    desc: 'Aero siri untuk ruang sederhana.',
    specs: ['HEPA + carbon filter.', 'Operasi senyap.'],
    benefits: ['Sesuai untuk bilik tidur.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS35GGW10.AML',
    name: 'Aero HIT',
    poster: 'assets/img/air-purifier/AS35GGW10.AML.jpg',
    price: 'RM45 / bulan',
    desc: 'Model HIT untuk fokus habuk halus.',
    specs: ['Nano carbon filter.', 'Light sensor.'],
    benefits: ['Auto adjust ikut cahaya / waktu.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS65GDWBO',
    name: 'Single Booster',
    poster: 'assets/img/air-purifier/AS65GDWBO.jpg',
    price: 'RM70 / bulan',
    desc: 'Single booster untuk bilik kecil.',
    specs: ['PM2.5 sensor.', 'Indicator tukar filter.'],
    benefits: ['Mudah pantau kualiti udara.'],
  },
  {
    cat: 'air-purifier',
    model: 'AS60GH',
    name: '360° HIT',
    poster: 'assets/img/air-purifier/AS60GH.jpg',
    price: 'RM50 / bulan',
    desc: 'HIT series untuk hygiene tinggi.',
    specs: ['UVnano.', 'Auto mode pintar.'],
    benefits: ['Kurang virus & bakteria udara.'],
  },

  // === WASHER ===
  {
    cat: 'washer',
    model: 'FV1450S2W',
    name: 'Front Load 10.5kg',
    poster: 'assets/img/washer/FV1450S2W.jpg',
    price: 'RM200 / bulan',
    desc: 'Front load dengan AI DD & TurboWash.',
    specs: ['AI DD – pilih corak basuhan auto.', 'TurboWash 360.'],
    benefits: ['Kain lebih tahan lama & jimat masa.'],
  },
  {
    cat: 'washer',
    model: 'F2520SNEKR',
    name: 'Front Load 20kg',
    poster: 'assets/img/washer/F2520SNEKR.jpg',
    price: 'RM300 / bulan',
    desc: 'Kapasiti besar untuk comforter & heavy load.',
    specs: ['Inverter motor.', 'Hygiene Steam.'],
    benefits: ['Kurang trip ke dobi layan diri.'],
  },
  {
    cat: 'washer',
    model: 'TV2517DV3B',
    name: 'Top Load 17kg',
    poster: 'assets/img/washer/TV2517DV3B.jpg',
    price: 'RM85 / bulan',
    desc: 'Top load mudah guna untuk keluarga.',
    specs: ['TurboDrum.', 'Smart Diagnosis.'],
    benefits: ['Sesuai rumah landed & keluarga ramai.'],
  },
  {
    cat: 'washer',
    model: 'TV2520SV9KR',
    name: 'Top Load 20kg',
    poster: 'assets/img/washer/TV2520SV9KR.jpg',
    price: 'RM100 / bulan',
    desc: 'Kapasiti besar untuk load mingguan.',
    specs: ['6 Motion.', 'Auto pre-wash.'],
    benefits: ['Basuh kuat tapi jaga kain.'],
  },
  {
    cat: 'washer',
    model: 'F2515RNTKAR',
    name: '15/8kg Washer Dryer',
    poster: 'assets/img/washer/F2515RNTKAR.jpg',
    price: 'RM140 / bulan',
    desc: 'Gabung washer + dryer dalam satu unit.',
    specs: ['Heat Pump Dryer.', 'Sensor Dry.'],
    benefits: ['Kering cepat & jimat ruang.'],
  },
  {
    cat: 'washer',
    model: 'FV1209D4W',
    name: '9/5kg Washer Dryer AI DD',
    poster: 'assets/img/washer/FV1209D4W.jpg',
    price: 'RM120 / bulan',
    desc: 'Washer-dryer dengan AI DD & Steam.',
    specs: ['Direct Drive motor.', 'Steam Refresh.'],
    benefits: ['Segar balik pakaian tanpa perlu basuh penuh.'],
  },

  // === DRYER ===
  {
    cat: 'dryer',
    model: 'VD-H9066WS',
    name: '9kg Heat Pump',
    poster: 'assets/img/dryer/VD-H9066WS.jpg',
    price: 'RM100 / bulan',
    desc: 'Dryer heat pump jimat tenaga.',
    specs: ['Auto Cleaning Condenser.', 'Wrinkle Care.'],
    benefits: ['Tak bergantung pada cuaca hujan/panas.'],
  },

  // === WASHTOWER ===
  {
    cat: 'washtower',
    model: 'WT2520MHGER',
    name: 'WashTower AI DD',
    poster: 'assets/img/washtower/WT2520MHGER.jpg',
    price: 'RM560 / bulan',
    desc: 'Washer + dryer bertingkat dalam satu menara.',
    specs: ['Center Control panel.', 'AI DD kedua-dua unit.'],
    benefits: ['Jimat ruang, ideal untuk condo moden.'],
  },

  // === AIRCOND (DUALCOOL + ARTCOOL) ===
  {
    cat: 'aircond',
    model: 'S3-Q09JAPPA',
    name: 'Dualcool 1.5HP',
    poster: 'assets/img/aircond/S3-Q09JAPPA.jpg',
    price: 'RM80 / bulan',
    desc: 'Aircond Dualcool untuk bilik tidur / bilik sederhana.',
    specs: ['Dual Inverter Compressor.', 'Fast Cooling.'],
    benefits: ['Jimat sehingga 70% tenaga.'],
  },
  {
    cat: 'aircond',
    model: 'S3-Q12JAPPA',
    name: 'Dualcool 1.5HP',
    poster: 'assets/img/aircond/S3-Q12JAPPA.jpg',
    price: 'RM90 / bulan',
    desc: 'Dualcool 1.5HP untuk bilik sederhana besar.',
    specs: ['ThinQ Wi-Fi.', 'Dehumidify mode.'],
    benefits: ['Boleh kawal guna app dari mana-mana.'],
  },
  {
    cat: 'aircond',
    model: 'S3-Q18KLPPA',
    name: 'Dualcool 2.0HP',
    poster: 'assets/img/aircond/S3-Q18KLPPA.jpg',
    price: 'RM150 / bulan',
    desc: '2.0HP untuk ruang tamu / ruang besar.',
    specs: ['Energy saving inverter.', 'Low noise operation.'],
    benefits: ['Sesuai untuk ruang keluarga utama.'],
  },
  {
    cat: 'aircond',
    model: 'S3-Q24K2PPA',
    name: 'Dualcool 2.5HP',
    poster: 'assets/img/aircond/S3-Q24K2PPA.jpg',
    price: 'RM180 / bulan',
    desc: '2.5HP untuk ruang tamu besar / open space.',
    specs: ['Powerful cooling.', 'Anti-corrosion fin.'],
    benefits: ['Stabil walau rumah hadap matahari.'],
  },
  {
    cat: 'aircond',
    model: 'S3-Q12JARPA',
    name: 'ArtCool 1.5HP',
    poster: 'assets/img/aircond/S3-Q12JARPA.jpg',
    price: 'RM130 / bulan',
    desc: 'ArtCool design premium untuk bilik / ruang tamu kecil.',
    specs: ['Glass panel design.', 'Voice control ready.'],
    benefits: ['Nampak macam wall art, bukan aircond biasa.'],
  },
  {
    cat: 'aircond',
    model: 'S3-Q24K2RPA',
    name: 'ArtCool 2.5HP',
    poster: 'assets/img/aircond/S3-Q24K2RPA.jpg',
    price: 'RM280 / bulan',
    desc: 'ArtCool 2.5HP untuk ruang tamu utama.',
    specs: ['Jet Mode cooling.', 'ThinQ AI integration.'],
    benefits: ['Estetik & sejuk padu untuk ruang besar.'],
  },

  // === TV ===
  {
    cat: 'tv',
    model: 'OLED77B5PSA',
    name: '77" OLED B5 4K',
    poster: 'assets/img/tv/OLED77B5PSA.jpg',
    price: 'RM1120 / bulan',
    desc: 'OLED 77" untuk home cinema serius.',
    specs: ['Dolby Vision.', 'webOS Smart.'],
    benefits: ['Hitam pekat, kontras tinggi.'],
  },
  {
    cat: 'tv',
    model: 'OLED65C3PSA',
    name: '65" OLED C3 4K',
    poster: 'assets/img/tv/OLED65C3PSA.jpg',
    price: 'RM780 / bulan',
    desc: 'OLED C3 untuk movie & gaming serius.',
    specs: ['120Hz Refresh.', 'NVIDIA G-Sync ready.'],
    benefits: ['Gaming smooth & responsif.'],
  },
  {
    cat: 'tv',
    model: 'QNED75',
    name: '75" QNED 4K',
    poster: 'assets/img/tv/QNED75.jpg',
    price: 'RM400 / bulan',
    desc: 'QNED untuk siaran sukan & TV harian.',
    specs: ['Quantum Dot.', 'Local Dimming.'],
    benefits: ['Warna cerah untuk ruang terang.'],
  },
  {
    cat: 'tv',
    model: 'Nano83',
    name: '65" NanoCell 4K',
    poster: 'assets/img/tv/Nano83.jpg',
    price: 'RM220 / bulan',
    desc: 'Mid-range NanoCell untuk keluarga.',
    specs: ['AI Processor.', 'Magic Remote.'],
    benefits: ['Mudah guna, value for money.'],
  },
  {
    cat: 'tv',
    model: '75QNED91TSA',
    name: '75" MiniLED QNED',
    poster: 'assets/img/tv/75QNED91TSA.jpg',
    price: 'RM230 / bulan',
    desc: 'QNED MiniLED untuk kontras lebih baik.',
    specs: ['Dimming Pro.', 'Dolby Atmos.'],
    benefits: ['HDR lebih hidup & detail.'],
  },
  {
    cat: 'tv',
    model: '65QNED87ASA',
    name: '65" QNED Evo AI',
    poster: 'assets/img/tv/65QNED87ASA.jpg',
    price: 'RM135 / bulan',
    desc: 'QNED Evo dengan AI Picture terkini.',
    specs: ['Dynamic Tone Mapping.', 'AI Picture.'],
    benefits: ['Upscale konten biasa ke nampak premium.'],
  },

  // === SOUNDBAR ===
  {
    cat: 'soundbar',
    model: 'S90TY',
    name: '570W 5.1.3ch',
    poster: 'assets/img/soundbar/S90TY.jpg',
    price: 'RM60 / bulan',
    desc: 'Soundbar dengan Dolby Atmos & rear speaker.',
    specs: ['Dolby Atmos.', 'WOW Synergy dengan LG TV.'],
    benefits: ['Rasa macam cinema di rumah.'],
  },

  // === STYLER ===
  {
    cat: 'styler',
    model: 'S3WF',
    name: 'TrueSteam Styler',
    poster: 'assets/img/styler/S3WF.jpg',
    price: 'RM180 / bulan',
    desc: 'Almari stim pakaian untuk sanitize & refresh.',
    specs: ['Moving Hanger.', 'Steam Sanitize.'],
    benefits: ['Kurang hantar dry clean, jimat masa & kos.'],
  },

  // === DISHWASHER ===
  {
    cat: 'dishwasher',
    model: 'DFC533FV',
    name: 'QuadWash TrueSteam Prime Silver',
    poster: 'assets/img/dishwasher/DFC533FV.jpg',
    price: 'RM130 / bulan',
    desc: 'Wi-Fi enabled, sesuai keluarga aktif.',
    specs: ['QuadWash 4 arms.', 'TrueSteam.', 'ThinQ app.'],
    benefits: ['Bersih 30% lebih, auto open dry.'],
  },
  {
    cat: 'dishwasher',
    model: 'DFC335HM',
    name: 'QuadWash Matte Black',
    poster: 'assets/img/dishwasher/DFC335HM.jpg',
    price: 'RM150 / bulan',
    desc: 'Dishwasher matte black dengan auto open door.',
    specs: ['Dual Zone.', 'EasyRack Plus.'],
    benefits: ['Kering natural & fleksibel ubah rak.'],
  },

  // === VACUUM (ONLY STANDARD) ===
  {
    cat: 'vacuum',
    model: 'A9T-RMAX',
    name: 'CordZero Standard',
    poster: 'assets/img/vacuum/A9T-RMAX.jpg',
    price: 'RM90 / bulan',
    desc: 'Cordless vacuum standard untuk rumah moden.',
    specs: ['2 bateri boleh tukar.', 'Pelbagai nozzle pembersihan.'],
    benefits: ['Sehingga ~90 min runtime, mudah cover satu rumah.'],
  },

  // === DEHUMIDIFIER (ONLY DD16GM) ===
  {
    cat: 'dehumidifier',
    model: 'DD16GM',
    name: '16L Dual Inverter',
    poster: 'assets/img/dehumidifier/DD16GM.jpg',
    price: 'RM70 / bulan',
    desc: 'Dehumidifier inverter senyap untuk elak lembap.',
    specs: ['Smart Control.', 'Bucket Full Alert.'],
    benefits: ['Jimat sehingga 40% tenaga & elak kulapuk.'],
  },
];

// Tambah index untuk modal
PRODUCTS.forEach((p, i) => {
  p._idx = i;
});

// Export ke window
window.CATEGORY_ORDER = CATEGORY_ORDER;
window.ICONS = ICONS;
window.PRODUCTS = PRODUCTS;
